### ISSUE TITLE
TypeError: An error occurred while processing a template

### ISSUE THREAD

**Issue by lakenen** [hansifer/grunt-file-info#3]
I am getting this error after I upgraded to node 0.12:

```
TypeError: An error occurred while processing a template (Cannot assign to read only property 'subarray' of [MY CODE]
    at Object.Ab [as gzipSync] (somepath/node_modules/grunt-file-info/node_modules/zlib-browserify/zlib.js:53:221)
    at Object.gzipSize (somepath/node_modules/grunt-file-info/tasks/file_info.js:199:39)
    at eval (/lodash/template/source[23]:9:20)
    at Function.template (somepath/node_modules/grunt/node_modules/lodash/lodash.js:3879:14)
    at Object.template.process (somepath/node_modules/grunt/lib/grunt/template.js:75:27)
    at Object.processInjectDest (somepath/node_modules/grunt-file-info/tasks/file_info.js:118:43)
    at Object.processInject (somepath/node_modules/grunt-file-info/tasks/file_info.js:84:25)
    at Object.<anonymous> (somepath/node_modules/grunt-file-info/tasks/file_info.js:49:23)
    at Object.<anonymous> (somepath/node_modules/grunt/lib/grunt/task.js:264:15)
    at Object.thisTask.fn (somepath/node_modules/grunt/lib/grunt/task.js:82:16)
```

Any idea why this is happening?

**Comment by megawac** [comment]
Getting this error as well

**Comment by sylvainpolletvillard** [comment]
+1, got this error too

**Comment by hansifer** [comment]
Fixed.
